title: Cristhiam Teran
description: Ideas and practices from a software engineer
author: Cristhiam Teran
logo: /static/img/avatar.png
github: https://github.com/foxhard
about: Software Developer

url: "https://streetcoder.dev"
baseurl: ""

allowsearch: true

disqus_shortname: the-street-developer
google_analytics: UA-130939916-1

share:
  twitter_username: streetcoder_dev
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
